apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: geneweaver-legacy-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: gcp-secrets-manager
  target:
    name: geneweaver-legacy-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_CLIENTSECRET
      remoteRef:
        key: "geneweaver_legacy_secrets"
        property: AUTH_CLIENTSECRET
    - secretKey:  APPLICATION_SECRET
      remoteRef:
        key: "geneweaver_legacy_secrets"
        property: APPLICATION_SECRET
