apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geneweaver-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: geneweaver-pv-rwm
  storageClassName: cloud-storage-rwm