version: '2'
services:
  web:
    build: 
      context: ../../website-py
      dockerfile: sample-configs/Dockerfile
    image: geneweaver:latest
    ports: 
     - "80:80"
     - "443:443"
    volumes: 
     - ../src:/srv/geneweaver/website-py/src
    depends_on:
     - sphinx
     - rabbitmq
     - postgres
    restart: unless-stopped
    container_name: geneweaver-web
    links:
     - postgres
  sphinx:
    image: leodido/sphinxsearch:2.2.9
    ports: 
     - "9306:9306"
     - "9312:9312"
    volumes:
     - /opt/compsci/geneweaver/sphinx-config:/usr/local/etc
    command: indexall.sh
    restart: unless-stopped
    container_name: geneweaver-sphinx
    links:
     - postgres
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "8080:15672"
    environment:
     - RABBITMQ_ERLANG_COOKIE='7gH3cB9vtK4j'
     - RABBITMQ_DEFAULT_USER=DenimWeft
     - RABBITMQ_DEFAULT_PASS=AosLeb3QC4PU9uxHz7z8Ga98
    restart: unless-stopped
    container_name: geneweaver-rabbitmq
  postgres:
    image: postgres:9.6
    volumes_from:
     - container:gwdb-ext:rw
    container_name: geneweaver-postgres

