version: '2'
services:
  web:
    build: 
      context: ../../website-py
      dockerfile: sample-configs/Dockerfile
    ports: 
     - "80:80"
     - "443:443"
    volumes: 
     - ../src:/srv/geneweaver/website-py/src
    depends_on:
     - sphinx
     - rabbitmq
  sphinx:
    image: leodido/sphinxsearch:2.2.9
    ports: 
     - "9306:9306"
     - "9312:9312"
    volumes:
     - /opt/compsci/geneweaver/sphinx-config:/usr/local/etc
    command: indexall.sh
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "8080:15672"
    environment:
     - RABBITMQ_ERLANG_COOKIE='7gH3cB9vtK4j'
     - RABBITMQ_DEFAULT_USER=DenimWeft
     - RABBITMQ_DEFAULT_PASS=AosLeb3QC4PU9uxHz7z8Ga98
