FROM python:2.7

MAINTAINER Alexander Berger <alexander.berger@jax.org>

RUN groupadd user \
 && useradd --create-home --home-dir /home/user -g user user \
 && mkdir /home/user/results

WORKDIR /home/user

ENV CELERY_VERSION 4.0.2

RUN pip install celery=="$CELERY_VERSION"

RUN { \
 echo 'import os'; \
 echo "BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://')"; \
} > celeryconfig.py

RUN apt-get update \
 && apt-get install -y gcc \
		       g++ \
                       make \
		       libboost-all-dev \
		       libcairo2-dev \
		       graphviz \
		       libffi6 \
		       libffi-dev \
		       libpqxx-dbg \
		       libpqxx-dev

COPY docker-configs /home/user/docker-configs

RUN pip install --upgrade pip \
 && pip install -r /home/user/docker-configs/requirements.txt

COPY ./ /home/user/tools/

RUN cd tools/TOOLBOX \
 && make \
 && cd ../.. \
 && cd tools/cpp_tools \
 && make \
 && cd ../.. \
 && chown -R user:user /home/user

ENV CELERY_BROKER_URL amqp://guest@rabbitmq

USER user
CMD ["celery", "-A", "tools.celeryapp", "worker"]
