version: '2.1'
services:
  web:
    image: csdocker.jax.org/geneweaver:latest
    healthcheck:
      test: ["CMD-SHELL", "cd", "..", "&&", "python", "-m", "unittest", "discover", "&&", "echo", "HEALTHCHECK PASSED"]
      interval: 12h
      timeout: 30s
      retries: 3
    ports: 
     - "80:80"
     - "443:443"
    volumes: 
     - '../src:/srv/geneweaver/website-py/src'
     - 'results:/srv/geneweaver/results'
    depends_on:
      sphinx:
        condition: service_started
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy
      celery:
        condition: service_started
    restart: unless-stopped
    container_name: geneweaver-web
    links:
     - postgres
     - rabbitmq
     - sphinx
  sphinx:
    image: leodido/sphinxsearch:2.2.9
    ports: 
     - "9306:9306"
     - "9312:9312"
    volumes:
     - './docker-configs/sphinx-configs:/usr/local/etc'
    command: indexall.sh
    restart: unless-stopped
    container_name: geneweaver-sphinx
    links:
     - postgres
    depends_on:
      postgres:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "8080:15672"
    environment:
     - RABBITMQ_ERLANG_COOKIE='7gH3cB9vtK4j'
    restart: unless-stopped
    container_name: geneweaver-rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: csdocker.jax.org/geneweaver-db:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "geneweaver", "-h", "postgres", "-U", "postgres", "-t", "10"]
      interval: 1m
      timeout: 15s
      retries: 3
    container_name: geneweaver-postgres
  celery:
    image: csdocker.jax.org/geneweaver-celery:latest
    links:
      - rabbitmq
      - postgres
    depends_on:
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes: 
     - 'results:/home/user/results'

volumes:
  results:
