#!/bin/bash
#compTests: Script to ...
#Created: Fri Sep 23 18:24:57 CDT 2016
mkdir testExes
g++ --std=c++11 -o testExes/testUnique testUnique.cpp
g++ --std=c++11 -o testExes/testSamples testSample.cpp
g++ --std=c++11 -o testExes/testCppOfRsMatch testMatchCopy.cpp
g++ --std=c++11 -o testExes/testIntersects testIntersectSizeFinder.cpp
exit 0
