apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  geneweaver-legacy-ingress
  annotations:
    # NOTE: When deploying a new instance, make sure to use the staging issuer first
    # so that you don't hit the rate limit for the production issuer.
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "geneweaver-prod.jax.org"
        - "geneweaver.jax.org"
        - "geneweaver.org"
        - "www.geneweaver.org"
        - "classic.geneweaver.org"
      secretName: geneweaver-prod-jax-org-tls
  rules:
    - host: geneweaver.jax.org
      http:
        paths:
          - backend:
              service:
                name: geneweaver-aon-api
                port:
                  number: 8000
            path: /aon/api
            pathType: Prefix
          - backend:
              service:
                name: geneweaver-api
                port:
                  number: 8000
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: geneweaver-ui
                port:
                  number: 80
            path: /next
            pathType: Prefix
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: geneweaver-legacy
                port:
                  number: 8000
    - host: "geneweaver.org"
      http:
        paths:
          - backend:
              service:
                name: geneweaver-aon-api
                port:
                  number: 8000
            path: /aon/api
            pathType: Prefix
          - backend:
              service:
                name: geneweaver-api
                port:
                  number: 8000
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: geneweaver-ui
                port:
                  number: 80
            path: /next
            pathType: Prefix
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: geneweaver-legacy
                port:
                  number: 8000
    - host: "geneweaver-prod.jax.org"
      http:
        paths:
          - backend:
              service:
                name: geneweaver-aon-api
                port:
                  number: 8000
            path: /aon/api
            pathType: Prefix
          - backend:
              service:
                name: geneweaver-api
                port:
                  number: 8000
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: geneweaver-ui
                port:
                  number: 80
            path: /next
            pathType: Prefix
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: geneweaver-legacy
                port:
                  number: 8000
    - host: "www.geneweaver.org"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: geneweaver-legacy
                port:
                  number: 8000
    - host: "classic.geneweaver.org"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: geneweaver-legacy
                port:
                  number: 8000